print("Taatilah peraturan itu")
print("Kerjakan sholat 5 waktu")
print("Selamat datang Ria")
print("Belajarlah dengan giat")
print("Cita-cita ku ingin menjadi polwan")
print("Saya mempunyai hobi berenang")
print("Ayahku seorang polisi")
print("Saya suka pedas")
print("Saya sekolah di smk harapan bangsa")
print("Kamu sangat cantik")
